image: debian:latest

variables:
  GIT_STRATEGY: clone

sync-to-github:
  stage: deploy
  only:
    - main
  before_script:
    - apt-get update && apt-get install -y git
  script:
    - git remote add github "https://${GITHUB_TOKEN}@github.com/jingminzhang/syncgitlabautogen.git"
    - git push github HEAD:refs/heads/main --force
  variables:
    GIT_DEPTH: 0